/*
 *
 * OpsContainer constants
 *
 */

export const DEFAULT_ACTION = 'app/OpsContainer/DEFAULT_ACTION';

export const GET_PLANS_REQUEST = 'app/OpsContainer/GET_PLANS_REQUEST';
export const GET_PLANS_SUCCESS = 'app/OpsContainer/GET_PLANS_SUCCESS';
export const GET_PLANS_FAILURE = 'app/OpsContainer/GET_PLANS_FAILURE';

export const GET_INITIATED_PLAN_REQUEST = 'app/OpsContainer/GET_INITIATED_PLAN_REQUEST';
export const GET_INITIATED_PLAN_SUCCESS = 'app/OpsContainer/GET_INITIATED_PLAN_SUCCESS';
export const GET_INITIATED_PLAN_FAILURE = 'app/OpsContainer/GET_INITIATED_PLAN_FAILURE';

export const UPDATE_OPS_DETAILS_REQUEST = 'app/OpsContainer/UPDATE_OPS_DETAILS_REQUEST';
export const UPDATE_OPS_DETAILS_SUCCESS = 'app/OpsContainer/UPDATE_OPS_DETAILS_SUCCESS';
export const UPDATE_OPS_DETAILS_FAILURE = 'app/OpsContainer/UPDATE_OPS_DETAILS_FAILURE';

export const GET_OPERATION_DETAILS = 'app/OpsContainer/GET_OPERATION_DETAILS';
export const GET_OPERATION_DETAILS_SUCCESS = 'app/OpsContainer/GET_OPERATION_DETAILS_SUCCESS';
export const GET_OPERATION_DETAILS_FAIL = 'app/OpsContainer/GET_OPERATION_DETAILS_FAIL';

export const UPDATE_OPERATION_COLLAPSE_DETAILS = 'app/OpsContainer/UPDATE_OPERATION_COLLAPSE_DETAILS';
export const UPDATE_TC_COLLAPSE_DETAILS = 'app/OpsContainer/UPDATE_TC_COLLAPSE_DETAILS';
export const UPDATE_NOK_OUTREACHED_COLLAPSE_DETAILS = 'app/OpsContainer/UPDATE_NOK_OUTREACHED_COLLAPSE_DETAILS';
export const UPDATE_SOCIAL_ASPECTS_COLLAPSE_DETAILS = 'app/OpsContainer/UPDATE_SOCIAL_ASPECTS_OUTREACHED_COLLAPSE_DETAILS';
export const UPDATE_EMERGENCIES_MILESTONES_COLLAPSE_DETAILS = 'app/OpsContainer/UPDATE_EMERGENCIES_MILESTONES_OUTREACHED_COLLAPSE_DETAILS';
export const UPDATE_SIMULATION_COLLAPSE_DETAILS = 'app/OpsContainer/UPDATE_SIMULATION_OUTREACHED_COLLAPSE_DETAILS';
export const UPDATE_CGHS_COLLAPSE_DETAILS = 'app/OpsContainer/UPDATE_CGHS_COLLAPSE_DETAILS';

export const UPDATE_OPERATION_COLLAPSE_DETAILS_SUCCESS = 'app/OpsContainer/UPDATE_OPERATION_COLLAPSE_DETAILS_SUCCESS';
export const UPDATE_OPERATION_COLLAPSE_DETAILS_FAIL = 'app/OpsContainer/UPDATE_OPERATION_COLLAPSE_DETAILS_FAIL';
