/*
 *
 * SocialTab constants
 *
 */

export const GET_SOCIAL_DATA_START = 'app/SocialTab/GET_SOCIAL_DATA_START';
export const GET_SOCIAL_DATA_SUCCESS = 'app/SocialTab/GET_SOCIAL_DATA_SUCCESS';
export const GET_SOCIAL_DATA_FAILURE = 'app/SocialTab/GET_SOCIAL_DATA_FAILURE';

export const POST_ELDER_PERSONA_START = 'app/SocialTab/POST_ELDER_PERSONA_START';
export const POST_ELDER_PERSONA_SUCCESS = 'app/SocialTab/POST_ELDER_PERSONA_SUCCESS';
export const POST_ELDER_PERSONA_FAILURE = 'app/SocialTab/POST_ELDER_PERSONA_FAILURE';

export const POST_EDU_QUAL_START = 'app/SocialTab/POST_EDU_QUAL_START';
export const POST_EDU_QUAL_SUCCESS = 'app/SocialTab/POST_EDU_QUAL_SUCCESS';
export const POST_EDU_QUAL_FAILURE = 'app/SocialTab/POST_EDU_QUAL_FAILURE';

export const POST_EMPLOYMENT_START = 'app/SocialTab/POST_EMPLOYMENT_START';
export const POST_EMPLOYMENT_SUCCESS = 'app/SocialTab/POST_EMPLOYMENT_SUCCESS';
export const POST_EMPLOYMENT_FAILURE = 'app/SocialTab/POST_EMPLOYMENT_FAILURE';

export const POST_LOCATION_START = 'app/SocialTab/POST_LOCATION_START';
export const POST_LOCATION_SUCCESS = 'app/SocialTab/POST_LOCATION_SUCCESS';
export const POST_LOCATION_FAILURE = 'app/SocialTab/POST_LOCATION_FAILURE';

export const POST_PREFERENCES_START = 'app/SocialTab/POST_PREFERENCES_START';
export const POST_PREFERENCES_SUCCESS = 'app/SocialTab/POST_PREFERENCES_SUCCESS';
export const POST_PREFERENCES_FAILURE = 'app/SocialTab/POST_PREFERENCES_FAILURE';

export const EMPLOYMENT_FORM_VALUE = 'app/SocialTab/EMPLOYMENT_FORM_VALUE';
export const LOCATION_FORM_VALUE = 'app/SocialTab/LOCATION_FORM_VALUE';
export const PREFERENCES_FORM_VALUE = 'app/SocialTab/PREFERENCES_FORM_VALUE';

